#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-ion-java
Version  : 1.0.2
Release  : 2
URL      : https://github.com/amzn/ion-java/archive/v1.0.2.tar.gz
Source0  : https://github.com/amzn/ion-java/archive/v1.0.2.tar.gz
Source1  : https://repo1.maven.org/maven2/software/amazon/ion/ion-java/1.0.2/ion-java-1.0.2.jar
Source2  : https://repo1.maven.org/maven2/software/amazon/ion/ion-java/1.0.2/ion-java-1.0.2.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-ion-java-data = %{version}-%{release}
Requires: mvn-ion-java-license = %{version}-%{release}

%description
# Amazon Ion Java
A Java implementation of the [Ion data notation](http://amznlabs.github.io/ion-docs/index.html).

%package data
Summary: data components for the mvn-ion-java package.
Group: Data

%description data
data components for the mvn-ion-java package.


%package license
Summary: license components for the mvn-ion-java package.
Group: Default

%description license
license components for the mvn-ion-java package.


%prep
%setup -q -n ion-java-1.0.2

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-ion-java
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-ion-java/LICENSE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/software/amazon/ion/ion-java/1.0.2
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/software/amazon/ion/ion-java/1.0.2/ion-java-1.0.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/software/amazon/ion/ion-java/1.0.2
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/software/amazon/ion/ion-java/1.0.2/ion-java-1.0.2.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/software/amazon/ion/ion-java/1.0.2/ion-java-1.0.2.jar
/usr/share/java/.m2/repository/software/amazon/ion/ion-java/1.0.2/ion-java-1.0.2.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-ion-java/LICENSE
